source 'https://github.com/CocoaPods/Specs.git'

platform :ios, 7.0

pod 'AFNetworking'
pod 'Lockbox'
pod 'Appirater'
pod 'HexColors'
pod 'SDWebImage'
pod 'GoogleAnalytics-iOS-SDK'
pod 'MXGoogleAnalytics'
pod 'Google-Mobile-Ads-SDK'
pod 'M13BadgeView', '~> 1.0.2'
pod 'Parse'
pod 'Facebook-iOS-SDK'
pod 'Reachability'
pod 'FCFileManager'
pod 'UIImage-ResizeMagick'
pod 'Block-KVO'
pod 'APParallaxHeader'
pod 'FCCurrentLocationGeocoder'